name: Executar Script às 23:00

on:
  schedule:
    - cron: '0 23 * * *'  # Executa às 23:00 todos os dias (UTC)

jobs:
  execute-script:
    runs-on: ubuntu-latest  # Usa um servidor Linux para execução
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3  # Baixa o código do repositório

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Define a versão do Python

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala as dependências do arquivo requirements.txt

      - name: Executar o script
        run: |
          python etl/pipeline_data_amazon.py  # Caminho corrigido para UNIX

