name: Executar Script Diariamente às 16h

on:
  schedule:
    - cron: '0 19 * * *'  # Executa às 19:00 UTC diariamente

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o script
        run: |
          python etl/pipeline_data_amazon.py




